Fix error detection in gray-box tests

diff --git a/test/test-gray-box b/test/test-gray-box
--- a/test/test-gray-box
+++ b/test/test-gray-box
@@ -20,6 +20,8 @@
 # You should have received a copy of the GNU General Public License
 # along with Pipe-o-matic.  If not, see <http://www.gnu.org/licenses/>.
 
+set -e  # Exit upon error.
+
 export TEST_ROOT=$(cd $(dirname "$0"); pwd)
 source "$TEST_ROOT"/lib/test-setup.sh
 
@@ -37,4 +39,9 @@ for case_dir in $(ls -r "$TEST_ROOT"/cases); do
     mkdir "$output_path"/expect
     ln -s .pmatic "$output_path"/execute/pmatic
     PYTHONPATH="$TEST_PYTHONPATH" "$test_case_path"/test "$output_path"
+    ERR=$?
+    if [[ $ERR != 0 ]]; then
+        echo $case_dir failed
+        exit $ERR
+    fi
 done
